name: "OpenAI ChatCompletions"
description: "Use OpenAI to generate responses (Chat+Completions)"
author: khanzzirfan
branding:
  icon: radio
  color: black
inputs:
  openai-api-key:
    description: "Your openai api key"
    required: true
  openai-mode:
    description: "To use 'chat' or 'completion' mode"
    required: true
    default: "completion"
  openai-params:
    description: "Parameters to send to openai's completion nodejs function"
    required: true
runs:
  using: "node20"
  main: "dist/index.js"
