name: Test output of OpenAI on Push
on:
  push:
    branches:
      - main
  workflow_dispatch: {}
jobs:
  openai-chat:
    name: OpenAI Chat Completion
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20
      - name: OpenAI
        uses: khanzzirfan/openai@v0.0.3
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          openai-mode: "completion"
          openai-params: '{"prompt":"Write a long essay on the following github commit message: ${{ github.event.commits.message}}", "model": "gpt-4o"}'
        id: openai
      - name: Print
        run: |
          echo  "${{ steps.openai.outputs.completion }}"
