name: Test output of OpenAI on Push
on:
  push:
    branches:
      - main
  workflow_dispatch: {}
jobs:
  openai-chat:
    name: OpenAI Chat Completion
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20
      - name: OpenAI
        uses: khanzzirfan/openai@v0.0.5
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          openai-params: '{
            "model": "gpt-4o",
            "store": true,
            "messages": [{"role": "user", "content": "Write a long essay on the following GitHub commit message: ${{ github.event.commits[0].message }}"}            ]          }'
        id: openai

      - name: Print
        run: |
          echo  "${{ steps.openai.outputs.completion }}"
